### ISSUE TITLE
Could you build a website to publish your guide?

### ISSUE THREAD

**Issue by JudgementH** [Xieyuschen/Awesome-Web-Server-Building#1]
Hi,
Your blog about web server building is amazing! 
Do you plan to build a website to record your blog for the best reading, or publish them on your personal website？

**Comment by xieyuschen** [comment]
Ah, thanks for your praising. I haven't any plan to publish it on website as a blog because I think it's better to treat those articles like drafts, not blog. They have been writen when I'm not familiar to detail of source code implement. As a result after finishing all of them those drafts must be arranged to make it friendly for nginx newer.
